LiveSPICEVst/EditorView.xaml, LiveSPICEVst/EditorView.xaml.cs, LiveSPICEVst/LiveSPICEPlugin.cs, LiveSPICEVst/LiveSPICEVst.csproj, LiveSPICEVst/SimulationProcessor.cs, LiveSPICEVst/VstProgramParameters.cs
I did some refactoring of the interface between the plugin code, the UI, and the SimulationProcessor class. I think it is cleaner now.
I also added in some error handling, and support for VST program load/save. It saves your selected schematic, as well as your settings for oversample/iterations. It does not current save pot/button values.
Oh, and I now have it defaulting to load schematics from MyDocuments.
=> Vst plugin updates

Asio/Stream.cs, LiveSPICE/Controls/Scope/SignalCollection.cs, LiveSPICE/Controls/Scope/SignalDisplay.cs, LiveSPICE/Controls/Simulation/Channel.cs, LiveSPICE/LiveSimulation.xaml.cs, LiveSPICE/Utils/Frequency.cs
When the buffer size is small, these allocations might be pretty significant.
=> Remove allocations and UI updates from the audio processing thread

LiveSPICEVst/EditorView.xaml.cs, LiveSPICEVst/LiveSPICEPlugin.cs, LiveSPICEVst/SimulationProcessor.cs
Currently, if you load a schematic, then reopen the open file dialog, it initializes to the path of the schematic, as expected. However, if you save the project using the VST plugin, close, reload the project, and then browse for a schematic, it will initialize to Documents\LiveSPICE\Examples instead of the path of the current schematic.
This PR fixes that by getting the schematic path from the plugin, instead of remembering it when it is loaded.
=> Fix initial directory of open file dialog for loaded plugin instances

Circuit/Components/Ground.cs
I've noticed that adding multiple ground symbols to the schematic creates additional nodes for them. This should fix that problem :)
=> Ground symbol as a named wire

LiveSPICE/Controls/Editor/SelectionTool.cs, LiveSPICE/Controls/Editor/WireTool.cs, LiveSPICE/Controls/SchematicViewer.xaml, LiveSPICE/Utils/ImageButton.cs, LiveSPICE/Utils/MenuItemIcon.cs, SchematicControls/ElementControl.cs, SchematicControls/SymbolControl.cs, SchematicControls/WireControl.cs
While working on vacuum tubes, I'm fixing some minor issues that I'm stumbling upon. 😃 This PR fixes some component misalignment issues that where caused by using a mix of `Guidelines`, `LayoutRounding` and `SnapToDevicePixels`. They are usefull for some extra sharp one-pixel wide separators, but when used with vector graphics they tend to cause issues with alignment, jittery image when zooming and panning, etc. I've also added freezing to all static pens, as it drastically improves rendering performance.
Before:
After:
=> Schematic rendering misalignment

LiveSPICE/Controls/Simulation/PotControl.cs
Sweep range should be limited to [0,1] interval.
=> Fix for PotControl limits.

LiveSPICEVst/LiveSPICEVst.csproj, MockVst/DummyHost.cs, MockVst/MockVst.csproj, README.md
This PR updates the VST to use the AudioPlugSharp NuGet packages, making out-of-the-box compilation much easier.
=> Update VST to use AudioPlugSharp NuGet packages

Benchmarks/Benchmarks.csproj, Benchmarks/GaussianElimination.cs, Benchmarks/Program.cs, Circuit/Simulation/Simulation.cs, LiveSPICE.sln, Tests/CommandLineExtensions.cs, Tests/Program.cs, Tests/Test.cs, Tests/Tests.csproj
Hi. I've tested how memory layout of arrays affects performance of the Gaussian elimination method in the inner loop of the simulation lambda and here are the results:
``` ini
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1110 (21H1/May2021Update)
Intel Core i7-8550U CPU 1.80GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100-preview.6.21355.2
[Host]     : .NET 6.0.0 (6.0.21.35212), X64 RyuJIT
Job-WMMCQC : .NET 6.0.0 (6.0.21.35212), X64 RyuJIT
InvocationCount=1  UnrollFactor=1  
```
|                  Method |  M |     Mean |   Error |  StdDev | Ratio | RatioSD | CacheMisses/Op | BranchMispredictions/Op | BranchInstructions/Op |      Gen 0 |     Allocated |
|------------------------ |--- |---------:|--------:|--------:|------:|--------:|---------------:|------------- …
=> Command line parameters parsing in Test, Gaussian elimination benchmarks.

.github/workflows/release.yml, .github/workflows/snapshot.yml, .github/workflows/test.yml, LiveSPICESetup.iss
This PR addresses the issue #172:
- Example of test: https://github.com/mdouchement/LiveSPICE/actions/runs/4747535761
- Example of snapshot: https://github.com/mdouchement/LiveSPICE/actions/runs/4747537811
- Example of release: https://github.com/mdouchement/LiveSPICE/releases/tag/v0.14-testouille
- The action is trigged when a new release is created in Github
~~VST part is omitted/disabled due to my lack of .NET knowledge but it can be fixed in another PR by someone else.~~
=> Github actions for builds and releases

Circuit/Components/Switch.cs, Circuit/Simulation/Simulation.cs, Circuit/Simulation/TransientSolution.cs, Tests/Circuits/SP3T.schx, Tests/Examples/Fender 5e3.schx
@Federerer I am curious to see what you think of this solution to #148. It adds a fake symbolic resistor for open switch circuits that has a large but finite value when solving for initial conditions, and is actually infinity when running the simulation.
This seems to fix all cases of initial conditions failing due to switches (two example circuits, plus your reproducer from #148).
I think this solution is quite a hack, and exposes some really weird behavior in the solver that needs a fix that seems like nonsense.
I am particularly curious if this eliminates the need for your random reordering of components to improve stability. It's possible that the extra stability is only needed because the simulation is starting so far away from the normal operating point...
=> Fix switch initial conditions

.github/workflows/release.yml
Embarrassingly, I can't figure out how to run the release workflow. I think it might run automatically when I make a release... but I'm not sure? I wanted to test the release before making it, so I'd rather have a way to run it manually too.
Trying to address #172.
=> Enable running release manually

.github/workflows/release.yml
Reverts dsharlet/LiveSPICE#175
This workflow can't run manually without a tag anyways.
=> Revert "Enable running release manually"

Asio/Asio.csproj, Audio/Audio.csproj, Circuit/Circuit.csproj, Tests/Properties/launchSettings.json, Util/Util.csproj, WaveAudio/WaveAudio.csproj
@Federerer let me know if you think this look right. I think even command line apps should target net6.0-windows due to significant performance improvements. (I ruled out the recent `CompareTo` fix as the cause of this improvement)
=> Drop library targets back to netstandard2.0

Circuit/Schematic/Element.cs, Circuit/Schematic/Schematic.cs, Circuit/Terminal.cs, LiveSPICE/Controls/Editor/WireTool.cs
This may work around the issue raised in #187. `Schematic.Deserialize` should be orders of magnitude faster with this branch.
The problem is when deserializing a circuit, the components and wires would be added as if they were added manually in the UI, rebuilding the nodes one at a time. The `ConnectedTo` algorithm was also quadratic. So I think the old behavior was two quadratic algorithms nested inside each other. How embarrassing :)
=> Optimize Schematic.Deserialize, a lot

Circuit/Components/VacuumTubes/Pentode.cs, Circuit/Components/VacuumTubes/Triode.cs
I've changed grid current calculation to method proposed by Cohen and Helie in [[1]](https://www.dafx.de/paper-archive/2010/DAFx10/CohenHelie_DAFx10_P45.pdf), [[2]](https://www.researchgate.net/profile/Thomas-Helie/publication/241433373_Measures_and_Parameter_Estimation_of_Triodes_for_the_Real-Time_Simulation_of_a_Multi-Stage_Guitar_Preamplifier/links/5459e0e30cf2bccc4912d9ba/Measures-and-Parameter-Estimation-of-Triodes-for-the-Real-Time-Simulation-of-a-Multi-Stage-Guitar-Preamplifier.pdf?origin=publication_detail) that we currently use in Pentodes. Polynomial smoothing helps with stability. I've also noticed, that Koren model gives better fitness e.g:
vs
(images are from [this tool](https://federerer.github.io/tube-model-fitter/))
I've added additional parameters to the model to …
=> koren model fixes

LiveSPICEVst/EditorView.xaml, LiveSPICEVst/EditorView.xaml.cs
Hello!
I've recently tried LiveSPICE and I find it very cool and very useful. After playing around with some simulations using the VST plugin inside Cockos REAPER, I found myself constantly having to click the `Load Schematic` button, search for the schematic file and then open it manually after doing some changes to the circuit.
Therefore, this pull request adds a `Reload` button to the VST, which I think is a much more convenient option to have, instead of manually reloading the schematic file every single time you update the circuit. Additionally, since adding a fourth button made everything look a bit squashed, I did a minor layout update, which you can see on the following image:
Please let me know if you have any comments and/or suggestions about this.
=> Add Reload button to LiveSPICE VST

Circuit/Schematic/Schematic.cs
Hopefully this helps the VST plugin to watch the file system more easily (#217).
=> Attempt to save schematics atomically

Circuit/Simulation/Simulation.cs, Circuit/Simulation/TransientSolution.cs
This change makes the solver much more aggressive about lifting solutions out of the non-linear solver. Previously, we would only search for solutions the order produced by `RowReduce`. Now, we instead repeatedly search for solutions that are independent of any remaining unknowns.
This change is a result of discussion with @andy-cytomic!
The impact to sim speed on example circuits is as follows:
Circuit | master | solver-fix |  
-- | -- | -- | --
59 Bassman Preamp+Tone Stack | 128.4 | 129.1 | 1.005451713
Big Muff Pi | 77.49 | 90.2 | 1.164021164
Boss Super Overdrive SD-1 | 505 | 779.6 | 1.543762376
Bridge Rectifier | 688.6 | 812.4 | 1.179785071
Common Cathode Triode Amplifier | 328.6 | 438.8 | 1.335362142
Common Emitter Transistor Amplifier | 921.2 | 1294 | 1.404689535
Dunlop Cry Baby …
=> Major speedup to simulations

LiveSPICE.sln, Tests/Plotting/Plot.cs, Tests/Plotting/Series.cs, Tests/Plotting/SeriesCollection.cs, Tests/Test.cs, Tests/Tests.csproj
I'm planning to replace ComputerAlgebra with a smaller, more focused expression + statement system for LiveSPICE. A minor first step: eliminate a dependency on ComputerAlgebra.Plotting, which only had one trivial reference to ComputerAlgebra in it.
=> Duplicate ComputerAlgebra.Plotting and remove dependency

LiveSPICEVst/LiveSPICEPlugin.cs, LiveSPICEVst/LiveSPICEVst.csproj, MockVst/MockVst.csproj
This updates the VST to the latest version of AudioPlugSharp. Plugins now run in isolated assembly load contexts so state remains independent when multiple instances of the plugin are loaded at the same time. 
Resolves https://github.com/dsharlet/LiveSPICE/issues/253
Resolves https://github.com/dsharlet/LiveSPICE/issues/244
=> Update VST to latest AudioPlugSharp
